# Generated by Django 3.2.4 on 2021-12-26 16:48

from django.db import migrations, models
import simplepro.components.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='配置简称')),
                ('content', models.TextField(verbose_name='配置内容')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
            },
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', simplepro.components.fields.CharField(max_length=200, verbose_name='引擎名称')),
                ('subdomain_discovery', simplepro.components.fields.SwitchField(default=True, null=True, verbose_name='扫描子域名')),
                ('certip_scan', simplepro.components.fields.SwitchField(default=False, null=True, verbose_name='cert_ip')),
                ('port_scan', simplepro.components.fields.SwitchField(default=True, null=True, verbose_name='扫描端口')),
                ('port_api', simplepro.components.fields.SwitchField(default=False, null=True, verbose_name='port_api[C段]')),
                ('fetch_url', simplepro.components.fields.SwitchField(default=True, null=True, verbose_name='扫描Web')),
                ('dir_file_search', simplepro.components.fields.SwitchField(default=False, verbose_name='目录扫描')),
                ('vuln_nuclei', simplepro.components.fields.SwitchField(default=False, verbose_name='nuclei扫描')),
                ('vuln_xray', simplepro.components.fields.SwitchField(default=False, verbose_name='xray被动扫描')),
                ('port_scan_type', models.CharField(choices=[('top10', 'top10'), ('top100', 'top100'), ('top1000', 'top1000'), ('all', '全端口')], default='top10', max_length=20, verbose_name='端口扫描模式')),
                ('dir_file_type', models.CharField(choices=[('top100', 'top100'), ('top2000', 'top2000'), ('top8000', 'top8000')], default='top100', max_length=20, verbose_name='目录扫描模式')),
            ],
            options={
                'verbose_name': '扫描引擎',
                'verbose_name_plural': '扫描引擎',
            },
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='字典名称')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='字典简称')),
                ('count', models.IntegerField(default=0, verbose_name='数量')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
            },
        ),
    ]
