# Generated by Django 3.2.4 on 2021-12-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.CharField(max_length=50, verbose_name='资产')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '黑名单资产',
                'verbose_name_plural': '黑名单资产',
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='ip地址')),
                ('is_cdn', models.BooleanField(default=False, verbose_name='是否是CDN')),
                ('tools', models.CharField(default='手工', max_length=50, null=True, verbose_name='来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': 'ip',
                'verbose_name_plural': 'ip',
            },
        ),
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500, verbose_name='url地址')),
                ('banner', models.CharField(blank=True, max_length=255, null=True, verbose_name='banner信息')),
                ('status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态码')),
                ('title', models.TextField(blank=True, null=True, verbose_name='标题')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='headers')),
                ('content_length', models.IntegerField(blank=True, default=0, null=True, verbose_name='内容长度')),
                ('screenshot_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='截屏')),
                ('webserver', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='指纹')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': 'web应用',
                'verbose_name_plural': 'web应用',
            },
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=200, unique=True, verbose_name='子域名')),
                ('domain_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='域名解析方式')),
                ('record', models.CharField(blank=True, max_length=2000, null=True, verbose_name='解析记录')),
                ('domain_ips', models.CharField(blank=True, max_length=2000, null=True, verbose_name='IP')),
                ('tools', models.CharField(default='手工导入', max_length=100, null=True, verbose_name='来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('scan_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
            },
        ),
        migrations.CreateModel(
            name='Rad2xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(blank=True, max_length=1000, null=True, verbose_name='target')),
                ('plugin', models.CharField(blank=True, max_length=100, null=True, verbose_name='plugin')),
                ('addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='漏洞链接')),
                ('payload', models.CharField(blank=True, max_length=1000, null=True, verbose_name='payload')),
                ('snapshot', models.TextField(blank=True, null=True, verbose_name='数据包')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详情')),
                ('mark', models.BooleanField(default=False, verbose_name='标记')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': 'nuclei',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=50, null=True, verbose_name='端口号')),
                ('ip_port', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IP2PORT')),
                ('status', models.CharField(default='open', max_length=255, verbose_name='端口状态')),
                ('service', models.CharField(max_length=255, verbose_name='端口服务')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('tools', models.CharField(default='naabu', max_length=50, null=True, verbose_name='工具来源')),
                ('ip', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.ip', verbose_name='IP')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '端口',
                'verbose_name_plural': '端口',
            },
        ),
        migrations.CreateModel(
            name='Nuclei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('templateID', models.CharField(max_length=500, verbose_name='漏洞名')),
                ('severity', models.CharField(max_length=100, verbose_name='级别')),
                ('matched', models.CharField(max_length=1000, verbose_name='漏洞链接')),
                ('detail', models.TextField(verbose_name='详情')),
                ('mark', models.BooleanField(default=False, verbose_name='标记')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': 'nuclei',
            },
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipc', models.CharField(db_index=True, max_length=100, verbose_name='C段')),
                ('ipc_count', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='目标C段主机数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.subdomain', verbose_name='域名'),
        ),
        migrations.CreateModel(
            name='FileLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='leak_url')),
                ('path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='泄露路径')),
                ('content_length', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='内容长度')),
                ('status_code', models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='状态码')),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='标题')),
                ('tools', models.CharField(default='fileleak', max_length=100, null=True, verbose_name='工具来源')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cms', models.CharField(blank=True, max_length=500, null=True, verbose_name='CMS')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': '文件泄露',
                'verbose_name_plural': '文件泄露',
            },
        ),
        migrations.CreateModel(
            name='CrawlerURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True, verbose_name='url')),
                ('method', models.CharField(blank=True, max_length=50, null=True, verbose_name='method')),
                ('header', models.TextField(blank=True, null=True, verbose_name='header')),
                ('b64_body', models.TextField(blank=True, null=True, verbose_name='b64_body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scans.scans', verbose_name='扫描任务')),
            ],
            options={
                'verbose_name': 'URL爬虫',
            },
        ),
    ]
