# Generated by Django 3.2.4 on 2021-12-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='targetApp.project', verbose_name='工程名'),
        ),
    ]
