# Generated by Django 3.2.4 on 2021-12-26 16:48

from django.db import migrations, models
import django.db.models.deletion
import simplepro.components.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanEngine', '0001_initial'),
        ('targetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_name', simplepro.components.fields.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='扫描任务名称')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='添加者')),
                ('scan_level', simplepro.components.fields.SliderField(default=10, verbose_name='扫描优先级')),
                ('celery_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='celery任务')),
                ('scan_status', models.CharField(choices=[('PENDING', '正在扫描'), ('FAILURE', '扫描失败'), ('RETRY', '正在重试'), ('SUCCESS', '扫描完成'), ('REVOKED', '任务撤销'), ('STARTED', '开始扫描')], default='0', max_length=10, verbose_name='扫描状态')),
                ('last_scan_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='最后扫描日期')),
                ('scan_type', simplepro.components.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scanEngine.enginetype', verbose_name='扫描类型')),
                ('target', simplepro.components.fields.TransferField(blank=True, help_text='选择扫描资产', to='targetApp.Target', verbose_name='扫描资产')),
            ],
            options={
                'verbose_name': '扫描任务',
                'verbose_name_plural': '扫描任务',
            },
        ),
    ]
